version: "2.3"

services:
 hadoop-base:
  build: 
    context: ./hadoop/base
    labels:
      description: "Base Image for Hadoop Nodes"
  image: hadoop-base:0.3 

 hadoop-namenode:
  build:
    context: ./hadoop/namenode
    labels:
      description: "Image for Hadoop NameNode"
  image: hadoop-namenode:0.3
  links:
     - "hadoop-base"

 hadoop-datanode:
  build:
    context: ./hadoop/datanode
    labels:
      description: "Image for Hadoop DataNode"
  image: hadoop-datanode:0.3
  links:
     - "hadoop-base"

 yarn-nodemanager:
  build:
    context: ./hadoop/nodemanager
    labels:
      description: "Image for Hadoop Node Manager"
  image: yarn-nodemanager:0.3
  links:
     - "hadoop-base"

 yarn-resourcemanger:
  build:
    context: ./hadoop/resourcemanager
    labels:
      description: "Image for Yarn Resource Manager"
  image: yarn-resourcemanager:0.3
  links:
     - "hadoop-base"

 yarn-historyserver:
  build:
    context: ./hadoop/historyserver
    labels:
      description: "Image for Yarn timeline Server"
  image: yarn-historyserver:0.3
  links:
     - "hadoop-base"
