version: "2.3"
services:     
  hadoop-namenode:
    image: hadoop-namenode:0.3
    container_name: hadoop-namenode
    hostname: hadoop-namenode.bigdatacluster
    mem_limit: ${HADOOP_NN_MEM_LIM}
    mem_reservation: ${HADOOP_NN_MEM_RES}
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    networks:
        bigdatacluster:
          aliases:
            - namenode.bigdatacluster.com
    environment:
      - CLUSTER_NAME=wasbhadoopcluster
    env_file:
      - ./bigdata-cluster.env
      - ./secrets.env  

  hadoop-datanode1:
    image: hadoop-datanode:0.3
    container_name: hadoop-datanode1
    hostname: hadoop-datanode1.bigdatacluster
    mem_limit: ${HADOOP_DN_MEM_LIM}
    mem_reservation: ${HADOOP_DN_MEM_RES}
    depends_on:
      hadoop-namenode :
         condition: service_healthy
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    networks:
        bigdatacluster:
          aliases:
            - datanode1.bigdatacluster.com
    env_file:
      - ./bigdata-cluster.env
      - ./secrets.env 

  hadoop-datanode2:
    image: hadoop-datanode:0.3
    container_name: hadoop-datanode2
    hostname: hadoop-datanode2.bigdatacluster
    mem_limit: ${HADOOP_DN_MEM_LIM}
    mem_reservation: ${HADOOP_DN_MEM_RES}
    depends_on:
      hadoop-namenode:
         condition: service_healthy
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    networks:
        bigdatacluster:
          aliases:
            - datanode2.bigdatacluster.com
    env_file:
      - ./bigdata-cluster.env
      - ./secrets.env


  hadoop-datanode3:
    image: hadoop-datanode:0.3
    container_name: hadoop-datanode3
    hostname: hadoop-datanode3.bigdatacluster
    mem_limit: ${HADOOP_DN_MEM_LIM}
    mem_reservation: ${HADOOP_DN_MEM_RES}
    depends_on:
      hadoop-namenode:
         condition: service_healthy
    volumes:
      - hadoop_datanode3:/hadoop/dfs/data
    networks:
        bigdatacluster:
          aliases:
            - datanode3.bigdatacluster.com
    env_file:
      - ./bigdata-cluster.env
      - ./secrets.env

  yarn-resourcemanager:
    image: yarn-resourcemanager:0.3
    container_name: yarn-resourcemanager
    hostname: yarn-resourcemanager.bigdatacluster
    mem_limit: ${YARN_RM_MEM_LIM}
    mem_reservation: ${YARN_RM_MEM_RES}
    networks:
        bigdatacluster:
          aliases:
            - resourcemanager.bigdatacluster.com
    depends_on:
      hadoop-namenode:
         condition: service_healthy
    env_file:
      - ./bigdata-cluster.env
      - ./secrets.env
  
  yarn-historyserver:
    image: yarn-historyserver:0.3
    container_name: yarn-historyserver
    hostname: yarn-historyserver.bigdatacluster
    mem_limit: ${YARN_HS_MEM_LIM}
    mem_reservation: ${YARN_HS_MEM_RES}
    depends_on:
      yarn-resourcemanager:
         condition: service_healthy
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    networks:
        bigdatacluster:
          aliases:
            - historyserver.bigdatacluster.com
    env_file:
      - ./bigdata-cluster.env
      - ./secrets.env 
  
  yarn-nodemanager1:
    image: yarn-nodemanager:0.3
    container_name: yarn-nodemanager1
    hostname: yarn-nodemanager1.bigdatacluster
    mem_limit: ${YARN_NM_MEM_LIM}
    mem_reservation: ${YARN_NM_MEM_RES}
    networks:
      bigdatacluster:
          aliases:
            - nodemanager1.bigdatacluster.com
    depends_on:
      yarn-resourcemanager:
         condition: service_healthy
    env_file:
      - ./bigdata-cluster.env
      - ./secrets.env

  yarn-nodemanager2:
    image: yarn-nodemanager:0.3
    container_name: yarn-nodemanager2
    hostname: yarn-nodemanager2.bigdatacluster
    mem_limit: ${YARN_NM_MEM_LIM}
    mem_reservation: ${YARN_NM_MEM_RES}
    networks:
      bigdatacluster:
          aliases:
            - nodemanager2.bigdatacluster.com
    depends_on:
      yarn-resourcemanager:
         condition: service_healthy
    env_file:
      - ./bigdata-cluster.env
      - ./secrets.env

  yarn-nodemanager3:
    image: yarn-nodemanager:0.3
    container_name: yarn-nodemanager3
    hostname: yarn-nodemanager3.bigdatacluster
    mem_limit: ${YARN_NM_MEM_LIM}
    mem_reservation: ${YARN_NM_MEM_RES}
    networks:
      bigdatacluster:
          aliases:
            - nodemanager3.bigdatacluster.com
    depends_on:
      yarn-resourcemanager:
         condition: service_healthy
    env_file:
      - ./bigdata-cluster.env
      - ./secrets.env  
   
volumes:
  hadoop_namenode:
          driver: local-persist
          driver_opts:
               mountpoint: /datadisk/dockervolumes/masters/hadoop/nn   
  hadoop_datanode1:
          driver: local-persist
          driver_opts:
               mountpoint: /datadisk/dockervolumes/workers/hadoop/dn1
  hadoop_datanode2:
          driver: local-persist
          driver_opts:
               mountpoint: /datadisk/dockervolumes/workers/hadoop/dn2
  hadoop_datanode3:
          driver: local-persist
          driver_opts:
               mountpoint: /datadisk/dockervolumes/workers/hadoop/dn3
  hadoop_historyserver:
          driver: local-persist
          driver_opts:
               mountpoint: /datadisk/dockervolumes/masters/yarn/hs
networks:
  bigdatacluster:
    external: true
